### ISSUE TITLE
[CLOSED] Aggro Distance

### ISSUE THREAD

**Issue by netherspite** [netherspite/cc-buglist#2307]
<a href="https://github.com/ccshiro"><img src="https://avatars2.githubusercontent.com/u/8135895?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ccshiro](https://github.com/ccshiro)**    
_Thursday Feb 11, 2016 at 14:28 GMT_  
_Originally opened as https://github.com/ccshiro/cc-buglist/issues/2307_

----

The formula for aggro distance (i.e. body pulling) is wrong.

**Comment by Earnestly** [comment]
This is still a problem.  The general aggro range is quite a bit higher than retail used to be.  It makes a lot of low level content borderline impossible to complete without help, see: https://github.com/netherspite/cc-buglist/issues/341#issuecomment-403316352

**Comment by netherspite** [comment]
Do you have any proofs for that?
I think this can be verified by comparing Joana's video guide with the current server behavior but I'm not sure where exactly this can be seen better.
