### ISSUE TITLE
Some escort NPCs ignore player combat

### ISSUE THREAD

**Issue by netherspite** [netherspite/cc-buglist#2563]
<a href="https://github.com/WhitePrideWorldWide"><img src="https://avatars2.githubusercontent.com/u/18603926?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [WhitePrideWorldWide](https://github.com/WhitePrideWorldWide)**    
_Friday Apr 22, 2016 at 09:43 GMT_  
_Originally opened as https://github.com/ccshiro/cc-buglist/issues/2563_

----

Umbrafen Village and Sunspring Post escorts don't assist the player in combat unless directly attacked.  Firewing Point and Bone Wastes escorts assist correctly.  My best guess is that it only happens with escorts with scripted enemy spawns on their path.

**Comment by alexzk1** [comment]
Seems I fixed it in commit 
https://github.com/netherspite/CCNext/commit/b04cf8c7314d497514fe4017fcc083049756a0e3
