### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by netherspite** [netherspite/cc-buglist#2571]
<a href="https://github.com/Dailybs"><img src="https://avatars3.githubusercontent.com/u/8177594?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Dailybs](https://github.com/Dailybs)**    
_Sunday Apr 24, 2016 at 10:34 GMT_  
_Originally opened as https://github.com/ccshiro/cc-buglist/issues/2571_

----

In Ashenvale I saw 2 coppers, and one of them was bugged, like 1st time you get copper, then nothing all the other times and was not disappearing.I guess you should check mining throughout Azeroth.Also other gathering profs.I didnt search all Ashenvale tho, just Farfarren river and timbermaws below ally town.So I dunno if it is buggy, but one node was for sure messed up :D

**Comment by alexzk1** [comment]
fixed
