### ISSUE TITLE
Mobs unable to find a path in instances

### ISSUE THREAD

**Issue by netherspite** [netherspite/cc-buglist#2597]
<a href="https://github.com/Summoning01"><img src="https://avatars2.githubusercontent.com/u/10939929?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Summoning01](https://github.com/Summoning01)**    
_Thursday Jul 28, 2016 at 09:36 GMT_  
_Originally opened as https://github.com/ccshiro/cc-buglist/issues/2597_

----

Looks like they get stuck in evade mode instead of running to the hunter.
[no_path.mp4](https://www.youtube.com/watch?v=ca9chQlNUak)

**Comment by alexzk1** [comment]
Patching is fixed in general, maps are changed including instances.
