### ISSUE TITLE
shiro you penis

### ISSUE THREAD

**Issue by netherspite** [netherspite/cc-buglist#2635]
<a href="https://github.com/Chulain"><img src="https://avatars1.githubusercontent.com/u/10247793?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Chulain](https://github.com/Chulain)**    
_Tuesday Oct 04, 2016 at 10:09 GMT_  
_Originally opened as https://github.com/ccshiro/cc-buglist/issues/2635_

----

no one cares if you can't release the server (yet), most of us stopped caring about the game long ago, we care about YOU & the project

the amount of effort the testers have put in this project is still nothing compared to what you have done but at the very least we deserve to know what's going on. Why would you keep us in the dark? 

stop being a dirty russian lover, get yo ass on irc and talk to us you maggot

**Comment by netherspite** [comment]
<a href="https://github.com/Chulain"><img src="https://avatars1.githubusercontent.com/u/10247793?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Chulain](https://github.com/Chulain)**  
_Tuesday Oct 04, 2016 at 10:11 GMT_

----

### 28 ‎december ‎2013, ‏‎20:57:06

![qcpulyt](https://cloud.githubusercontent.com/assets/10247793/19070459/a342149a-8a2b-11e6-8c81-ca90c4e24b65.jpg)

### ‎19 ‎january ‎2013, ‏‎17:48:08

![wowscrnshot_011913_174808](https://cloud.githubusercontent.com/assets/10247793/19629807/4004b624-997d-11e6-899b-95fa0a730e63.jpg)

**Comment by netherspite** [comment]
<a href="https://github.com/denman1999"><img src="https://avatars2.githubusercontent.com/u/18452849?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [denman1999](https://github.com/denman1999)**  
_Tuesday Oct 04, 2016 at 14:37 GMT_

----

I have read and accept the content of the paste.

**Comment by netherspite** [comment]
<a href="https://github.com/Evolvee"><img src="https://avatars2.githubusercontent.com/u/1942409?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Evolvee](https://github.com/Evolvee)**  
_Thursday Oct 06, 2016 at 20:02 GMT_

----

I have read and accept the content of the paste.

**Comment by alexzk1** [comment]
Some human's chat.
