### ISSUE TITLE
pet not following

### ISSUE THREAD

**Issue by netherspite** [netherspite/cc-buglist#2642]
<a href="https://github.com/Summoning01"><img src="https://avatars2.githubusercontent.com/u/10939929?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Summoning01](https://github.com/Summoning01)**    
_Sunday Oct 16, 2016 at 07:45 GMT_  
_Originally opened as https://github.com/ccshiro/cc-buglist/issues/2642_

----

no idea what caused it. happens quite often
https://www.youtube.com/watch?v=UpAtmaU13_w
edit: looking at the vid again at 0.25 speed... seems llike the pet growled shortly before the worg died (hard to tell otherwise since growl cooldown isn't displayed). that may be the cause.

**Comment by alexzk1** [comment]
Source video deleted. Not sure what author means.
