### ISSUE TITLE
[CLOSED] "You are in Combat"

### ISSUE THREAD

**Issue by netherspite** [netherspite/cc-buglist#974]
<a href="https://github.com/Kinglundh"><img src="https://avatars3.githubusercontent.com/u/12054923?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kinglundh](https://github.com/Kinglundh)**    
_Monday Jul 06, 2015 at 16:59 GMT_  
_Originally opened as https://github.com/ccshiro/cc-buglist/issues/974_

----

Was playing shattered halls Heroic and when we came to the Champion mobs, some of us couldnt get out of combat, so we werent able to drink / ress etc etc.
Could it be because of we used fear on mobs through the instance before and might have feared a critter or something? :)

**Comment by netherspite** [comment]
<a href="https://github.com/Jigodian"><img src="https://avatars1.githubusercontent.com/u/6188133?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Jigodian](https://github.com/Jigodian)**  
_Monday Jul 06, 2015 at 17:45 GMT_

----

Did the combat state eventually disappear or did it just go on forever?

**Comment by netherspite** [comment]
<a href="https://github.com/Chulain"><img src="https://avatars1.githubusercontent.com/u/10247793?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Chulain](https://github.com/Chulain)**  
_Monday Jul 06, 2015 at 18:49 GMT_

----

critters reset after a short time as far as i know

**Comment by netherspite** [comment]
<a href="https://github.com/Kinglundh"><img src="https://avatars3.githubusercontent.com/u/12054923?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kinglundh](https://github.com/Kinglundh)**  
_Monday Jul 06, 2015 at 19:04 GMT_

----

It went on forever, atleast 30 minutes then we called it.

**Comment by netherspite** [comment]
<a href="https://github.com/SubzeroEUsupermodel"><img src="https://avatars3.githubusercontent.com/u/9557139?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SubzeroEUsupermodel](https://github.com/SubzeroEUsupermodel)**  
_Wednesday Jul 15, 2015 at 11:33 GMT_

----

Check combat log for any indication. Use tab to target nearby mobs, see if any is targeting you.

**Comment by netherspite** [comment]
<a href="https://github.com/Yagrulol"><img src="https://avatars0.githubusercontent.com/u/12082872?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Yagrulol](https://github.com/Yagrulol)**  
_Saturday Jul 25, 2015 at 17:11 GMT_

----

As for chullians post,
Not the July4th test but the one before that i noticed that critters did not reset after a short while.
I had to kill them to get out of combat.
If nothing has changed for the critters, this could've been the issue.

**Comment by netherspite** [comment]
<a href="https://github.com/ccshiro"><img src="https://avatars2.githubusercontent.com/u/8135895?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ccshiro](https://github.com/ccshiro)**  
_Sunday Feb 14, 2016 at 12:45 GMT_

----

Fixed in #1460.

**Comment by Earnestly** [comment]
This may not be fixed, although I do vaguely remember this happening during retail too.

After killing Warbringer O'mrogg you seem to be constant stuck in combat: ![combat](https://ptpb.pw/2zPy.jpg)
